# Generated by Django 2.0.3 on 2018-03-10 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmaker',
            name='canAdd',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nakki',
            name='endtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nakki',
            name='starttime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
