# Generated by Django 2.0.3 on 2018-03-11 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nakit', '0002_auto_20180311_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='nakki',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
