# Generated by Django 2.0.3 on 2019-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nakit', '0003_nakki_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaker',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Eventmaker',
        ),
    ]
